import React, { useState, useEffect, useRef } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, SafeAreaView, ScrollView, TextInput, Platform, Alert, Animated } from 'react-native';
import { useRouter } from 'expo-router';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { LinearGradient } from 'expo-linear-gradient';
import { 
  Search, 
  Filter, 
  Award, 
  FileText, 
  Users, 
  ChevronRight,
  Clock,
  AlertCircle,
  Bot,
  Sparkles
} from 'lucide-react-native';


// Mock data for government schemes
const mockSchemes = [
  {
    id: '1',
    name: 'PM Kisan Samman Nidhi',
    description: 'Direct income support to eligible farmer families',
    eligibility: 'Small and marginal farmers with landholding up to 2 hectares',
    action: 'Apply online',
    deadline: '30 June 2025',
    category: 'Income Support',
    icon: '💰',
    cropType: 'All crops'
  },
  {
    id: '2',
    name: 'Pradhan Mantri Fasal Bima Yojana',
    description: 'Crop insurance scheme to provide financial support to farmers',
    eligibility: 'All farmers including tenant farmers and sharecroppers',
    action: 'Visit insurance office',
    deadline: '30 days after sowing',
    category: 'Insurance',
    icon: '🛡️',
    cropType: 'All crops'
  },
  {
    id: '3',
    name: 'Soil Health Card Scheme',
    description: 'Soil testing and nutrient management for farms',
    eligibility: 'All farmers',
    action: 'Upload soil sample',
    deadline: 'Ongoing',
    category: 'Soil Health',
    icon: '🌱',
    cropType: 'All crops'
  },
  {
    id: '4',
    name: 'Paramparagat Krishi Vikas Yojana',
    description: 'Promotion of organic farming practices',
    eligibility: 'Farmer groups of 10 or more',
    action: 'Apply online',
    deadline: '31 March 2025',
    category: 'Organic Farming',
    icon: '🌿',
    cropType: 'All crops'
  },
  {
    id: '5',
    name: 'National Mission for Sustainable Agriculture',
    description: 'Climate resilient agriculture through sustainable practices',
    eligibility: 'All farmers practicing sustainable methods',
    action: 'Visit district office',
    deadline: '30 September 2025',
    category: 'Sustainable Agriculture',
    icon: '🌍',
    cropType: 'All crops'
  },
  {
    id: '6',
    name: 'Rashtriya Krishi Vikas Yojana',
    description: 'State level planning and project implementation',
    eligibility: 'State government agricultural departments',
    action: 'Apply through state',
    deadline: '31 December 2025',
    category: 'State Level',
    icon: '🏛️',
    cropType: 'All crops'
  }
];

export default function GovernmentSchemesScreen() {
  const [userData, setUserData] = useState<any>(null);
  const [schemes, setSchemes] = useState(mockSchemes);
  const [filteredSchemes, setFilteredSchemes] = useState(mockSchemes);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('All');
  const [aiRecommendations, setAiRecommendations] = useState<any[]>([]);
  const [demoText, setDemoText] = useState('');
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [showDemo, setShowDemo] = useState(true);
  
  const router = useRouter();
  const typingAnimation = useRef(new Animated.Value(0)).current;
  const typingText = "Based on your profile, I recommend applying for the PM Kisan Samman Nidhi scheme. This provides direct income support of ₹6,000 per year to small and marginal farmers like yourself.";
  const utteranceRef = useRef<any>(null);
  const lastSpokenIndex = useRef(0);

  useEffect(() => {
    loadUserData();
  }, []);

  useEffect(() => {
    if (showDemo) {
      startDemo();
    }
    
    return () => {
      if (utteranceRef.current) {
        window.speechSynthesis.cancel();
      }
    };
  }, [showDemo]);

  const loadUserData = async () => {
    try {
      const data = await AsyncStorage.getItem('userData');
      if (data) {
        const parsedData = JSON.parse(data);
        setUserData(parsedData);
        generateAIRecommendations(parsedData);
      }
    } catch (error) {
      console.error('Error loading user data:', error);
    }
  };

  // Generate AI recommendations based on user profile
  const generateAIRecommendations = (userData: any) => {
    // In a real app, this would be generated by an AI model
    // For now, we'll use mock logic based on user data
    const recommendations = [];
    
    // Recommend PM Kisan for all farmers
    recommendations.push({
      schemeId: '1',
      reason: 'Income support for all farmers',
      priority: 'High',
      match: '100%'
    });
    
    // Recommend crop insurance for all farmers
    recommendations.push({
      schemeId: '2',
      reason: 'Protection against crop loss',
      priority: 'High',
      match: '100%'
    });
    
    // Recommend soil health card for all farmers
    recommendations.push({
      schemeId: '3',
      reason: 'Improve soil fertility and productivity',
      priority: 'Medium',
      match: '100%'
    });
    
    // Conditional recommendations based on user data
    if (userData.landSize && parseFloat(userData.landSize) <= 2) {
      recommendations.push({
        schemeId: '1',
        reason: 'Perfect match for your land size (up to 2 hectares)',
        priority: 'High',
        match: '95%'
      });
    }
    
    if (userData.cropType && userData.cropType.toLowerCase().includes('organic')) {
      recommendations.push({
        schemeId: '4',
        reason: 'Aligned with your organic farming practices',
        priority: 'High',
        match: '90%'
      });
    }
    
    setAiRecommendations(recommendations);
  };

  // Start the demo animation and speech
  const startDemo = () => {
    // Reset states
    setDemoText('');
    setIsSpeaking(true);
    lastSpokenIndex.current = 0;
    
    // Start typing animation
    typingAnimation.setValue(0);
    
    Animated.timing(typingAnimation, {
      toValue: typingText.length,
      duration: typingText.length * 50, // Adjust speed as needed
      useNativeDriver: false,
    }).start(() => {
      // Animation completed
      setIsSpeaking(false);
    });
    
    // Start speech synthesis
    if (Platform.OS === 'web' && 'speechSynthesis' in window) {
      // We'll handle speech synthesis in the text update listener
    } else {
      // Fallback for non-web platforms
      setTimeout(() => {
        setIsSpeaking(false);
      }, typingText.length * 50);
    }
  };

  // Filter schemes based on search query and category
  useEffect(() => {
    let result = schemes;
    
    if (searchQuery) {
      const query = searchQuery.toLowerCase();
      result = result.filter(scheme => 
        scheme.name.toLowerCase().includes(query) ||
        scheme.description.toLowerCase().includes(query) ||
        scheme.category.toLowerCase().includes(query) ||
        scheme.cropType.toLowerCase().includes(query)
      );
    }
    
    if (selectedCategory !== 'All') {
      result = result.filter(scheme => scheme.category === selectedCategory);
    }
    
    setFilteredSchemes(result);
  }, [searchQuery, selectedCategory, schemes]);

  const categories = ['All', ...Array.from(new Set(mockSchemes.map(scheme => scheme.category)))];

  // Get scheme by ID for recommendations
  const getSchemeById = (id: string) => {
    return schemes.find(scheme => scheme.id === id);
  };

  // Subscribe to animation updates
  useEffect(() => {
    const listenerId = typingAnimation.addListener(({ value }) => {
      const currentIndex = Math.floor(value);
      const newText = typingText.substring(0, currentIndex);
      setDemoText(newText);
      
      // Speak each word as it's typed
      if (Platform.OS === 'web' && 'speechSynthesis' in window) {
        const words = newText.split(' ');
        const lastWords = typingText.substring(0, lastSpokenIndex.current).split(' ');
        
        // Check if we have a new word to speak
        if (words.length > lastWords.length && currentIndex > lastSpokenIndex.current) {
          const newWord = words[words.length - 1];
          if (newWord && newWord.trim() !== '') {
            const utterance = new SpeechSynthesisUtterance(newWord);
            utterance.rate = 1.0;
            utterance.pitch = 1.0;
            utterance.volume = 1.0;
            
            utterance.onend = () => {
              utteranceRef.current = null;
            };
            
            utterance.onerror = () => {
              utteranceRef.current = null;
            };
            
            window.speechSynthesis.speak(utterance);
            utteranceRef.current = utterance;
          }
        }
        
        lastSpokenIndex.current = currentIndex;
      }
    });
    
    return () => {
      typingAnimation.removeListener(listenerId);
    };
  }, []);

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView style={styles.scrollView} showsVerticalScrollIndicator={false}>
        {/* Header */}
        <LinearGradient
          colors={['#2E7D32', '#4CAF50']}
          style={styles.header as any}
        >
          <View style={styles.headerContent}>
            <Text style={styles.headerTitle}>Government Schemes</Text>
            <Text style={styles.headerSubtitle}>Access subsidies and benefits for farmers</Text>
          </View>
        </LinearGradient>

        {/* Search and Filter */}
        <View style={styles.searchSection}>
          <View style={styles.searchContainer}>
            <Search size={20} color="#6B7280" style={styles.searchIcon} />
            <TextInput
              style={styles.searchInput}
              placeholder="Search schemes by name, crop, or category"
              value={searchQuery}
              onChangeText={setSearchQuery}
            />
          </View>
          
          <TouchableOpacity style={styles.filterButton}>
            <Filter size={20} color="#FFFFFF" />
            <Text style={styles.filterButtonText}>Filter</Text>
          </TouchableOpacity>
        </View>

        {/* Category Filter */}
        <ScrollView 
          horizontal 
          showsHorizontalScrollIndicator={false} 
          style={styles.categoryScroll}
          contentContainerStyle={styles.categoryScrollContent}
        >
          {categories.map((category) => (
            <TouchableOpacity
              key={category}
              style={[
                styles.categoryButton,
                selectedCategory === category && styles.categoryButtonActive
              ]}
              onPress={() => setSelectedCategory(category)}
            >
              <Text style={[
                styles.categoryButtonText,
                selectedCategory === category && styles.categoryButtonTextActive
              ]}>
                {category}
              </Text>
            </TouchableOpacity>
          ))}
        </ScrollView>

        {/* AI Demo Section */}
        {showDemo && (
          <View style={styles.aiSection}>
            <View style={styles.sectionHeader}>
              <Bot size={20} color="#2E7D32" />
              <Text style={styles.sectionTitle}>KrushiAI Assistant</Text>
            </View>
            
            <View style={styles.demoCard}>
              <LinearGradient
                colors={['#E8F5E9', '#C8E6C9']}
                style={styles.demoGradient}
              >
                <View style={styles.demoHeader}>
                  <View style={styles.aiIconContainer}>
                    <Bot size={24} color="#2E7D32" />
                  </View>
                  <View style={styles.demoInfo}>
                    <Text style={styles.demoTitle}>KrushiAI</Text>
                    <View style={styles.statusContainer}>
                      {isSpeaking ? (
                        <>
                          <View style={styles.speakingIndicator} />
                          <Text style={styles.statusText}>Speaking...</Text>
                        </>
                      ) : (
                        <Text style={styles.statusText}>Thinking...</Text>
                      )}
                    </View>
                  </View>
                </View>
                
                <View style={styles.demoContent}>
                  <Text style={styles.demoText}>{demoText}</Text>
                  {isSpeaking && (
                    <View style={styles.cursorContainer}>
                      <Text style={styles.cursor}>|</Text>
                    </View>
                  )}
                </View>
                
                <TouchableOpacity 
                  style={styles.closeDemoButton}
                  onPress={() => setShowDemo(false)}
                >
                  <Text style={styles.closeDemoText}>Dismiss</Text>
                </TouchableOpacity>
              </LinearGradient>
            </View>
          </View>
        )}

        {/* AI Recommendations */}
        {!showDemo && (
          <View style={styles.aiSection}>
            <View style={styles.sectionHeader}>
              <Bot size={20} color="#2E7D32" />
              <Text style={styles.sectionTitle}>AI Recommendations</Text>
            </View>
            
            {aiRecommendations.length > 0 ? (
              aiRecommendations.map((rec, index) => {
                const scheme = getSchemeById(rec.schemeId);
                if (!scheme) return null;
                
                return (
                  <View key={index} style={styles.recommendationCard}>
                    <LinearGradient
                      colors={['#E8F5E9', '#C8E6C9']}
                      style={styles.recommendationGradient}
                    >
                      <View style={styles.recommendationHeader}>
                        <View style={styles.schemeIconContainer}>
                          <Text style={styles.schemeIcon}>{scheme.icon}</Text>
                        </View>
                        <View style={styles.recommendationInfo}>
                          <Text style={styles.schemeName}>{scheme.name}</Text>
                          <View style={styles.matchContainer}>
                            <Sparkles size={14} color="#4CAF50" />
                            <Text style={styles.matchText}>{rec.match} match</Text>
                          </View>
                        </View>
                      </View>
                      
                      <Text style={styles.reasonText}>{rec.reason}</Text>
                      
                      <View style={styles.priorityContainer}>
                        <Text style={styles.priorityText}>Priority: {rec.priority}</Text>
                      </View>
                      
                      <TouchableOpacity style={styles.applyButton}>
                        <Text style={styles.applyButtonText}>Apply Now</Text>
                        <ChevronRight size={16} color="#FFFFFF" />
                      </TouchableOpacity>
                    </LinearGradient>
                  </View>
                );
              })
            ) : (
              <View style={styles.emptyState}>
                <Text style={styles.emptyStateText}>No AI recommendations available</Text>
              </View>
            )}
          </View>
        )}

        {/* Schemes List */}
        <View style={styles.schemesSection}>
          <View style={styles.sectionHeader}>
            <Award size={20} color="#2E7D32" />
            <Text style={styles.sectionTitle}>Available Schemes</Text>
          </View>
          
          {filteredSchemes.length === 0 ? (
            <View style={styles.emptyState}>
              <Text style={styles.emptyStateText}>No schemes found matching your criteria</Text>
            </View>
          ) : (
            filteredSchemes.map((scheme) => (
              <View key={scheme.id} style={styles.schemeCard}>
                <View style={styles.schemeHeader}>
                  <Text style={styles.schemeIcon}>{scheme.icon}</Text>
                  <View style={styles.schemeInfo}>
                    <Text style={styles.schemeName}>{scheme.name}</Text>
                    <Text style={styles.schemeDescription}>{scheme.description}</Text>
                  </View>
                </View>
                
                <View style={styles.schemeDetails}>
                  <View style={styles.detailRow}>
                    <Users size={16} color="#6B7280" />
                    <Text style={styles.detailText}>{scheme.eligibility}</Text>
                  </View>
                  
                  <View style={styles.detailRow}>
                    <FileText size={16} color="#6B7280" />
                    <Text style={styles.detailText}>Action: {scheme.action}</Text>
                  </View>
                  
                  <View style={styles.deadlineRow}>
                    <Clock size={16} color={scheme.deadline === 'Ongoing' ? '#4CAF50' : '#FF9800'} />
                    <Text style={[
                      styles.deadlineText,
                      scheme.deadline === 'Ongoing' ? styles.deadlineOngoing : styles.deadlinePending
                    ]}>
                      {scheme.deadline === 'Ongoing' ? 'Ongoing' : `Deadline: ${scheme.deadline}`}
                    </Text>
                    {scheme.deadline !== 'Ongoing' && (
                      <View style={styles.deadlineBadge}>
                        <Text style={styles.deadlineBadgeText}>!</Text>
                      </View>
                    )}
                  </View>
                </View>
                
                <TouchableOpacity style={styles.applyButton}>
                  <Text style={styles.applyButtonText}>Apply Now</Text>
                  <ChevronRight size={16} color="#FFFFFF" />
                </TouchableOpacity>
              </View>
            ))
          )}
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F0FDF4',
  },
  scrollView: {
    flex: 1,
  },
  header: {
    padding: 24,
    paddingTop: Platform.OS === 'ios' ? 44 : 24,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  headerContent: {
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 8,
    textAlign: 'center',
  },
  headerSubtitle: {
    fontSize: 16,
    color: 'rgba(255, 255, 255, 0.9)',
    textAlign: 'center',
    lineHeight: 22,
  },
  searchSection: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    gap: 12,
    marginBottom: 16,
  },
  searchContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: '#1F2937',
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2E7D32',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 6,
  },
  filterButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  categoryScroll: {
    marginBottom: 16,
  },
  categoryScrollContent: {
    paddingHorizontal: 16,
    gap: 12,
  },
  categoryButton: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  categoryButtonActive: {
    backgroundColor: '#2E7D32',
    borderColor: '#2E7D32',
  },
  categoryButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6B7280',
  },
  categoryButtonTextActive: {
    color: '#FFFFFF',
  },
  aiSection: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 16,
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1F2937',
  },
  demoCard: {
    borderRadius: 16,
    overflow: 'hidden',
  },
  demoGradient: {
    padding: 20,
    borderRadius: 16,
  },
  demoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
  },
  aiIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  demoInfo: {
    flex: 1,
  },
  demoTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1F2937',
  },
  statusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  speakingIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#4CAF50',
  },
  statusText: {
    fontSize: 12,
    color: '#6B7280',
  },
  demoContent: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  demoText: {
    fontSize: 16,
    color: '#1F2937',
    lineHeight: 24,
    flex: 1,
  },
  cursorContainer: {
    width: 2,
    height: 20,
    backgroundColor: '#2E7D32',
    marginLeft: 2,
    marginTop: 2,
  },
  cursor: {
    color: '#2E7D32',
  },
  closeDemoButton: {
    alignSelf: 'flex-end',
    backgroundColor: 'rgba(46, 125, 50, 0.1)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  closeDemoText: {
    color: '#2E7D32',
    fontWeight: '600',
  },
  recommendationCard: {
    marginBottom: 16,
    borderRadius: 16,
    overflow: 'hidden',
  },
  recommendationGradient: {
    padding: 20,
    borderRadius: 16,
  },
  recommendationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  schemeIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  schemeIcon: {
    fontSize: 20,
  },
  recommendationInfo: {
    flex: 1,
  },
  matchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  matchText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#2E7D32',
  },
  reasonText: {
    fontSize: 14,
    color: '#1F2937',
    lineHeight: 20,
    marginBottom: 16,
  },
  priorityContainer: {
    marginBottom: 16,
  },
  priorityText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#4CAF50',
    backgroundColor: 'rgba(76, 175, 80, 0.1)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  schemesSection: {
    marginHorizontal: 16,
    marginBottom: 16,
  },
  schemeCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  schemeHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 16,
  },
  schemeInfo: {
    flex: 1,
  },
  schemeName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1F2937',
    marginBottom: 4,
  },
  schemeDescription: {
    fontSize: 14,
    color: '#6B7280',
    lineHeight: 20,
  },
  schemeDetails: {
    gap: 12,
    marginBottom: 20,
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  detailText: {
    flex: 1,
    fontSize: 14,
    color: '#1F2937',
    lineHeight: 20,
  },
  deadlineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  deadlineText: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
  },
  deadlineOngoing: {
    color: '#4CAF50',
  },
  deadlinePending: {
    color: '#FF9800',
  },
  deadlineBadge: {
    backgroundColor: '#FF9800',
    width: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  deadlineBadgeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  applyButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#2E7D32',
    borderRadius: 12,
    paddingVertical: 14,
    gap: 8,
  },
  applyButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  emptyState: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyStateText: {
    fontSize: 16,
    color: '#6B7280',
    textAlign: 'center',
  },
});